### ISSUE TITLE
Can not find "from pokemon_showdown_accounts import id_dict"

### ISSUE THREAD

**Issue by ghost** [akashsara/meta-discovery#1]
Hello,

First of all great repository and it is great to find people working on Pokemon showdown as well. I would like to ask for this line which causes me errors because i can not find the module.

Can you help me how to install module "pokemon_showdown_accounts".
Thank you

**Comment by ghost** [comment]
I am not sure if you are alerted when I opened an issue so i would like to ping. @akashsara 

Thank you again.
 
With Regards

**Comment by akashsara** [comment]
Hey @tugayapucu, `pokemon_showdown_accounts` isn't an extra module. Just create a `pokemon_showdown_accounts.py` file in the src directory to store your Pokemon Showdown credential info. You'll need a username and password that you created as well as some additional details such as the path to your model and any kwargs if necessary. I'm out of town at the moment so I can't pull up a specific example, but if you can ping again next week, I should be able to show you an example.

**Comment by akashsara** [comment]
Closing this issue as the user seems to have deleted their account.
